name: tvg-landing
on:
  push:
    branches: [develop, master]
  pull_request:
    branches: [develop]
  workflow_dispatch:

env:
  GH_USER: ${{ secrets.GH_USER }}
  GH_TOKEN: ${{ secrets.GH_TOKEN }}

defaults:
  run:
    shell: bash

jobs:
  build:
    if: ${{ success() && github.event_name != 'pull_request' && github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: upload ui artifact
        uses: actions/upload-artifact@v2.2.4
        if: ${{ success() && github.event_name != 'pull_request' && (github.ref == 'refs/heads/develop' || github.ref == 'refs/heads/master') }}
        with:
          name: dist_ui
          path: ./dist

  deploy_stg_westeurope:
    if: ${{ success() && github.event_name != 'pull_request' && github.ref == 'refs/heads/develop' }}
    runs-on: ubuntu-latest
    needs: [build]
    environment: stg
    name: deploy stg westeurope
    steps:
      - name: download ui artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: "dist_ui"
          path: ./dist

      - name: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.DEPLOYMENT_TOKEN_WESTEUROPE }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist"
          api_location: ""
          output_location: ""
          skip_app_build: true

  deploy_prod_westeurope:
    if: ${{ success() && github.event_name != 'pull_request' && github.ref == 'refs/heads/master' }}
    runs-on: ubuntu-latest
    needs: [build]
    environment: prod
    name: deploy prod westeurope
    steps:
      - name: download ui artifact
        uses: actions/download-artifact@v2.0.10
        with:
          name: "dist_ui"
          path: ./dist

      - name: deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.DEPLOYMENT_TOKEN_WESTEUROPE }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: "upload"
          app_location: "dist"
          api_location: ""
          output_location: ""
          skip_app_build: true